action.configuration.commerce_bulk_variation_duplicate:
  type: action_configuration_default
  label: 'Configuration for the Duplicate variation action'
action.configuration.commerce_bulk_variation_priceadjust:
  type: action_configuration_default
  label: 'Configuration for the Adjust price action'
action.configuration.commerce_bulk_variation_zdelete:
  type: action_configuration_default
  label: 'Configuration for the Delete variations action'
action.configuration.commerce_bulk_variation_hook:
  type: action_configuration_default
  label: 'Configuration for the Pass to hook action'
action.configuration.commerce_bulk_variation_priceset:
  type: action_configuration_default
  label: 'Configuration for the Set price action'
action.configuration.commerce_bulk_variation_sku:
  type: action_configuration_default
  label: 'Configuration for the Change SKUs action'
action.configuration.commerce_bulk_variation_status:
  type: action_configuration_default
  label: 'Configuration for the Change status action'
action.configuration.commerce_bulk_variation_top:
  type: action_configuration_default
  label: 'Configuration for the Move to top action'
action.configuration.commerce_bulk_variation_title:
  type: action_configuration_default
  label: 'Configuration for the Change title action'
action.configuration.commerce_bulk_attribute_value_top:
  type: action_configuration_default
  label: 'Configuration for the Move to top action'
action.configuration.commerce_bulk_attribute_value_name:
  type: action_configuration_default
  label: 'Configuration for the Change or add names action'
action.configuration.commerce_bulk_attribute_value_zdelete:
  type: action_configuration_default
  label: 'Configuration for the Delete attributes action'
action.configuration.commerce_bulk_term_duplicate:
  type: action_configuration_default
  label: 'Configuration for the Duplicate term action'
action.configuration.commerce_bulk_term_zdelete:
  type: action_configuration_default
  label: 'Configuration for the Delete terms action'
action.configuration.commerce_bulk_order_zanonymize:
  type: action_configuration_default
  label: 'Configuration for the Anonymize Orders action'
field.widget.settings.commerce_bulk_sku:
  type: mapping
  label: 'Commerce Creator SKU format settings'
  mapping:
    custom_label:
      type: label
      label: 'Custom label'
    uniqid_enabled:
      type: boolean
      label: 'Enable unique auto SKU values generation'
    more_entropy:
      type: boolean
      label: 'More unique'
    hide:
      type: boolean
      label: 'Hide SKU'
    prefix:
      type: label
      label: 'SKU prefix'
    suffix:
      type: label
      label: 'SKU suffix'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'
    maximum:
      type: integer
      label: 'The maximum of SKU values in one go'
